name: ci

on:
  push:
    branches:
      - 'master'
      - 'github-action'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: "JoooostB"
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      -
        name: Build and push slim
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/slim.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jbruchon/jdupes:latest
            ghcr.io/jbruchon/jdupes:${{ github.ref_name }}            
      -
        name: Build and push alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/alpine.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/joooostb/jdupes:alpine
            ghcr.io/joooostb/jdupes:${{ github.ref_name }}-alpine
